# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5886dc846396f29dccfcafd65a6e56c36191e54539c969c86ea2ec98c8b6432a33a93fcf5538baeccecb8a133effa56e72243e69d21d27118a62bae75e05fc85

test:
  secret_key_base: 4cd0f799e917b85cd842aaf78a7683737175b9dae8ce8bd704a58e7528016728ae2f23634ff35d5005d84c53393285b4d97cbfa5d197291e8e3c4629c0d55a7a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
